"""empty message

Revision ID: 6e30f4525daa
Revises: 
Create Date: 2025-07-25 21:36:57.538139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e30f4525daa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_model', schema=None) as batch_op:
        batch_op.drop_column('accepted')
        batch_op.drop_column('upvotes')

    # ### end Alembic commands ###
